converted all array() calls to [], changed some formatting, etc.
LibreCodeCoop/LSTelegramNotify pull request #10
Opened 2020-10-19 05:21 UTC by naneri

* Converted all array() calls to [], to provide consistency across the file, as both array() and [] have been used. 
* added dockblocks to methods and properties to describe what methods/properties 
* formatted the code for readability

2020-10-19 16:38 UTC, vitormattos requested changes
Do you know PHPCS? Is a good moment to put in this project validating the source using PSR12.

One suggestion is to put the command to run PHPCS in script block of composer.json like this:  https://github.com/LyseonTech/dou-collector/blob/master/composer.json#L28

2020-10-19 16:38 UTC, vitormattos commented on LSTelegramNotify.php
> +     *
Empty? I suggest to put a description about this event for follow the pr objective or maintain without this docblock. Also is possible put annotation of type of return.

2020-10-19 16:38 UTC, vitormattos commented on LSTelegramNotify.php
> +     *
the same of before.

2020-10-20 04:04 UTC, naneri commented
@vitormattos concerning the Method descriptions - I am not 100% sure that I would describe those correctly. Also dockblocks did not generate any return type, because none of the methods returns anythings

2020-10-20 12:05 UTC, vitormattos commented
To use a pattern of docblock, I recomend to install [psalm](https://psalm.dev/) in this PR

To define pattern of coding, I recomend PHPCS.

Different people may want different standards. Using tools to define industry standards is the best way.

2020-10-21 15:40 UTC, vitormattos commented
Good! You will implement PHPCS or another static analyses tool in this PR?

2020-10-21 15:42 UTC, naneri commented
@vitormattos I have PSR-12 code style as a preset in PHPStorm, though it seems like very different to the way the repo was before the pull requests. Concerning adding a static analyzer in this PR, was not planning to do that.

2020-10-21 15:43 UTC, naneri commented on LSTelegramNotify.php
> +     *
added void return type

2020-10-21 15:45 UTC, merged

2020-10-21 15:45 UTC, vitormattos commented
very good contribution